### ISSUE TITLE
MultExpEstimation Parameter multiplicity

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#102]
The vector of P has to be the same across experiments (if I understand correctly).

Therefore, should the line [eg: 120-Mult..Exp..Estimator.py]
```python
       for i in self.experiments:
            for k,v in six.iteritems(self.model.experiment[i].P):
                #: do stuff
```
Be done only for self.experiments[0]?
So the reduced hessian is constructed for C, S and P, but which P? P[exp1] or P[exp2]....
I mention this bc k_aug reports inconsistent number of dof_v. I think is because P[exp1] == P[exp2].

**Comment by mchlshort** [comment]
Hi @dthierry, you are correct. If you reference the section where I did the same for sipopt, you will find the correct version where I do checks to determine the global versus local parameters. I am sure there are a number of errors in the k_aug setup as I did most of the testing and development for sipopt.

**Comment by dthierry** [comment]
Ah, thanks @mchlshort I didn't realize there were global parameters.
