### ISSUE TITLE
Pyomo 5.6.8 breaks kipet

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#115]
It has been observed that pyomo 5.6.8 breaks kipet. 
I believe a major update has taken place. 
Kuan-Han should have it fixed.

**Comment by mchlshort** [comment]
Hi @dthierry and @kuanhanl,

I think that I had this issue a couple months ago. It requires changing   _implicit_sets in Results_Loader with v.index_set().set_tuple

I am not sure if that is everything, but at least this was a problem for me!

**Comment by kuanhanl** [comment]
Hi @mchlshort,

Yes, you are right. That's one of the bugs. There is also another one when running Ex_5_sim_fe_by_fe.py and I am trying to fix it.

**Comment by dthierry** [comment]
Thanks guys :purple_heart:

**Comment by kuanhanl** [comment]
Bugs were all fixed and tests passed.

**Comment by dthierry** [comment]
Thanks @kuanhanl !
