### ISSUE TITLE
Parameter estimation with k_aug and non_absorbing species fails

### ISSUE THREAD

**Issue by schenkch** [salvadorgarciamunoz/kipet#122]
Claire was trying to use k_aug for the parameter estimation with non_absorbing species and ran into some issues regarding the number of DOFs.
I reproduced it by running Ex_6_non_absorbing.py with k_aug instead of ipopt and get similar errors. 
Somehow I thought that that was fixed with the new version of k_aug but I guess I was wrong and that just fixed the issue for the multiple experiments.
If we can not fix this, I think we should at least include an example for how to run that case with sipopt and mention it somewhere. 
`
> EXIT: Optimal Solution Found.
>        13.31 seconds required for solver
>         0.00 seconds required to read logfile 
>         0.02 seconds required to read solution file
>         0.04 seconds required for postsolve
> W[K_AUG]...	[K_AUG_ASL]No n_rhs declared
> W[K_AUG]...	[K_AUG_ASL]Target log10mu:= -11.
> [K_AUG] written by D.T. @2018
> 
> W[K_AUG]...	[K_AUG_ASL]No f_timestamp suffix declared, Fallback to default writing mode.
> I[K_AUG]...	[K_AUG_ASL] Filename for dot_sens dot_in_.in
> : I[K_AUG]...	[K_AUG_ASL]File read succesfull
> I[K_AUG]...	[K_AUG_ASL]Number of Right hand sides 0
> I[K_AUG]...	[K_AUG_ASL]Number of Right hand sides: 0
> I[K_AUG]...	[K_AUG_ASL]Number of variables       : 3505
> I[K_AUG]...	[K_AUG_ASL]Number of constraints     : 3303
> I[K_AUG]...	[K_AUG_ASL]Number of valid n_dof     : 202
> I[K_AUG]...	[ADJUST_MU]log10(mu) computed=-4.072927394894833 at var_i=600
> I[K_AUG]...	[ADJUST_MU]log10(mu) close to the target	-3.0950210100532742 at var_i=601
> I[K_AUG]...	[FIND_INEQUALITIES]summary: eq: 3303, leq: 0, geq: 0 
> I[K_AUG]...	[K_AUG_ASL]Nonzeroes in the sparse Jacobian 9003
> I[K_AUG]...	[GET_HESS_ASL]Objective found
> I[K_AUG]...	[GET_HESS_ASL]Nonzeroes in the sparse hessian 123000
> I[K_AUG]...	[GET_HESS_ASL]Minimization problem detected
> I[K_AUG]...	[GET_HESS_ASL]Current objective 13010.659230
> I[K_AUG]...	[GET_HESS_ASL]Missing nz in the Hessian of the Lag: 2105
> I[K_AUG]...	[K_AUG_ASL]Barrier term added.
> I[K_AUG]...	[K_AUG_ASL]MC19 scaling...
> I[K_AUG]...	[ASSM_RHS_RH]According to the suffixes declared dof is 802 
> E[K_AUG]...	[ASSM_RHS_RH]No valid number of n_dof declared
> ERROR: Solver (asl) returned non-zero return code (255)
`

**Comment by kwmcbride** [comment]
This is probably old, but I fixed this in the recent update to KIPET. The reason was because of the additional constraints used to set C equal to Z when creating the subset Cs. These were redundant and ended up adding too many constraints, which causes k_aug to fail. If you use sIpopt, these extra constraints are identified and don't become noticeable. 

In the current version of KIPET, there is no longer a subset used for the non-absorbing species and the correct number of contraints and variables is used in the model.
