### ISSUE TITLE
Getting error when running Ex1_ode_sim.py

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#126]
I get the following error when running Ex1_ode_sim.py
<img width="778" alt="Screen Shot 2020-06-25 at 7 03 43 PM" src="https://user-images.githubusercontent.com/7705554/85804081-b9a54100-b716-11ea-801e-7d42372a4f54.png">

The kipet version is the latest on github, I just installed it in my machine. The version of python, pyomo and info on my operating system
<img width="728" alt="Screen Shot 2020-06-25 at 7 05 27 PM" src="https://user-images.githubusercontent.com/7705554/85804138-dccff080-b716-11ea-8c3c-2d302cffab5f.png">

The jupyter notebook where I was trying this example is in this [location](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/Ex1_ode_sim_wk.py.ipynb) with all the code

Please let me know if I am missing some step in running this code.

Shankar

**Comment by kwmcbride** [comment]
I would try to run this using pyomo 5.6.9 first and see if it works.

**Comment by notesofdabbler** [comment]
Thanks. Installing pyomo 5.6.9 (along with downgrading pyUtilib to 5.8.0) worked. It looks like just downgrading to pyomo 5.6.9 doesn't work since it is incompatible with pyUtilib 6.0.0

**Comment by schenkch** [comment]
I actually discovered the same thing with pyomo5.6.6 and pyUtilib6.0.0 yesterday. I think it would be a good idea to exclude these combinations in the setup.py and requirements.txt file until they provide a fix.

**Comment by notesofdabbler** [comment]
Using the appropriate versions of pyomo and pyUtilib as discussed in the thread above fixes the issue.
