### ISSUE TITLE
DAE toolbox vs. manual collocation

### ISSUE THREAD

**Issue by schenkch** [salvadorgarciamunoz/kipet#13]
Is manual collocation even intended to be part of kipet? I did not find a single file which does not use the DAE toolbox. Are there any?

**Comment by mchlshort** [comment]
As far as I am aware there was never any intention to include that. I might be wrong though. Going through the source code I could only find the Pyomo DAE toolbox being used.

**Comment by dthierry** [comment]
That is correct. Would manual collocation be more useful?
We now have the first draft `fe_factory` which intends to provide a framework for marching forward finite per finite element with pyomo.dae. Although, it hasn't been merged into the main branch.

**Comment by schenkch** [comment]
Thanks. For now, I don't think so but it is definitely something we can discuss about again in detail.
