### ISSUE TITLE
Parameter confidence intervals in Ex_7_conc_input_conf_k_aug.py seem too wide

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#132]
When I run the example [Ex_7_conc_input_conf_k_aug.py](https://github.com/salvadorgarciamunoz/kipet/blob/master/kipet/examples/Ex_7_conc_input_conf_k_aug.py), I get the confidence intervals for k1 and k2 as:
```
Confidence intervals:
k1 (-33.423743265165804,33.87390686949457)
k2 (-515.018256768277,517.0584740517689)
```
This doesn't seem right. I wanted to check if I am doing something wrong. The jupyter notebook where I ran this example is in this [location](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/Ex_7_conc_input_conf_k_aug_wk.ipynb).

I also saw that there is a way to use pyNumero to get reduced hessian in estimationPotential. But I wasn't sure how to use pyNumero here instead of k_aug to check if I get the same results.

**Comment by kwmcbride** [comment]
It would seem that I broke something in the variance calculations. I am looking into where and should find it pretty soon.

**Comment by kwmcbride** [comment]
At the moment, EstimationPotential only uses PyNumero. At some point in the near future I will be writing it to use k_aug since we have more control over its development.

**Comment by kwmcbride** [comment]
I found the issue and have submitted a pull request to incorporate the fix.

**Comment by notesofdabbler** [comment]
Thanks. I tried the example again and now it seems to be fine.
```
Confidence intervals:
k1 (0.22630611417543584,0.22707403946042443)
k2 (1.0280192738950906,1.0324734524512933)
```
I had couple of more syntax questions:
1. Is it possible to get the covariance matrix of parameters
2. How do we get the objective value at the end of parameter fitting

**Comment by kwmcbride** [comment]
That should not be much of an issue. I can simply add those to the ResultsObject so that they are generally available. I'll look into this tomorrow.
