### ISSUE TITLE
Handling heterogeneous data in MultipleExperimentsEstimator

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#134]
It seems like MultipleExperimentsEstimator is not able to handle heterogeneous data (subset of species measured or each species measured at different times. The issue looks similar to #128 for estimating single experiments (which is resolved now). It seems to occur at the step when after fitting individual experiments, it tries to fit all of them and gives an error at this line from MultipleParameterEstimator.py

<img width="901" alt="Screen Shot 2020-08-07 at 6 18 47 AM" src="https://user-images.githubusercontent.com/7705554/89636017-f1ef8180-d875-11ea-8319-9b13842ea125.png">

**Comment by kwmcbride** [comment]
In my recent update I did not touch the MultipleExperimentsEstimator module (I assume you mean this one). My goal is to have a single module handle all of the objective functions such as this so that they are uniformly handled. I'm fairly sure this fails here due to the for loop over m.meas_times. Eventually, I will work on this module to update it as well. Afterwards, this shouldn't be an issue.

**Comment by notesofdabbler** [comment]
For the time being, I tried the same fix as with the single experiment estimation and modified portion of code in MultipleExperimentsEstimator.py at line 2144 as follows:
```
                def rule_objective(m):
                    obj = 0
#                    for t in m.meas_times:
#                        obj += sum((m.C[t, k] - m.Z[t, k]) ** 2 / self.variances[exp][k] for k in list_components)
                    for t,v in m.C.items():
                        k = t[1]
                        if not np.isnan(value(v)):
                            obj += (m.C[t] - m.Z[t])**2 / self.variances[exp][k] 

                    return m.error == obj
```
That seems to work. I have an example of trying with this modification in this [notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/multexpt_fit_subset_data.ipynb).

**Comment by kwmcbride** [comment]
That's basically the fix I am writing into it. Just iterate through the C index and not through the global measurement times index. I am moving the objectives to a separate module for this so that they are consistent across all other modules.

**Comment by kwmcbride** [comment]
This should be handled in the latest update to Kipet.
