### ISSUE TITLE
Fixing input variables from trajectory

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#136]
I created a small fed batch example where a reagent is added over a period of time in this [notebook ](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/ABC_fedbatch_sim.ipynb) drawing on using `input_subs` from [Ex_5_sim_fe_by_fe_multjumpsandinputs.py](https://github.com/salvadorgarciamunoz/kipet/blob/master/kipet/examples/Ex_5_sim_fe_by_fe_multjumpsandinputs.py). But when I use the command `sim.fix_from_trajectory` to fix the input flowrate, it somehow doesn't take it as intended (I have shown it in the notebook). Then I manually fixed it. I wasn't sure if I was doing something wrong in usage of `sim.fix_from_trajectory`.

**Comment by kwmcbride** [comment]
I have recreated your error and think that there is an error in the way the linear interpolation in the fix_from_trajectory method. I have replaced it with something similar that works. It uses the same strategy as before, in that a linear function between the times is assumed. I will be adding an option as well to allow for an immediate change, if desired. I will make this available as a branch (traj_fix) on my repository before integrating it into the master branch.

**Comment by notesofdabbler** [comment]
Thanks for looking into this. I don't need this immediately but just wanted to list it since I encountered it. I can directly specify it in the code for now.

**Comment by kwmcbride** [comment]
Well, I already put in a fix for it. I don't like to wait too long to fix issues like this in cases where you simply expect it to work.

**Comment by notesofdabbler** [comment]
Thanks for fixing this
