### ISSUE TITLE
subset_lambdas = A_set option bug for VarianceEstimator.run_opt

### ISSUE THREAD

**Issue by mchlshort** [salvadorgarciamunoz/kipet#14]
In the paper by Weifeng, during the variance estimator, for large problems he suggests that you use a subset of the wavelengths in order to speed up the estimation process.

When this is implemented in some of the examples (specifically the Examples/Paper/ any of the replication studies) the way that subset_lambdas is calculated using the parameter A_set does not seem to do anything. No matter what subset you choose, it seems to always select all wavelengths. 

It does not affect the solutions, but this is still not quite right and bugs me a little. Please check to see if I am right that this is the case and let me know if you can think of a fix.

**Comment by dthierry** [comment]
Could you provide me with an example where subset_lambdas is not all available lambdas?

I have seen the `Varianceestimator.py` and on line 257 The objective is being changed according to the elements of `set_A`. Now this might be buggy, but I'll have to confirm it.

**Comment by mchlshort** [comment]
I think that the problem is just the way that the set_A was defined in the examples themselves (labelled "A_set" in the replicate examples). I seem to have fixed it in the examples in which the set_A was actually used: all you have to do to make it work is to actually just change the final part of the line from "if i%7" to "if (i%7 == 0)". So a really simple fix... Seems to work fine now, but in all the examples where this is used, the same thing was done. I will update them in the examples and check that they still run before pushing.

**Comment by mchlshort** [comment]
Ok, should be all fixed now.
