### ISSUE TITLE
Parameter estimation for a fed-batch example not working

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#141]
I was trying a small fed batch example to fit a single reaction. I am not sure what I am doing wrong but the rate constant doesn't change from the initial estimate. The example is in this [notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/ABC_fedbatch_parmest.ipynb). I would appreciate any pointers on what I might be doing wrong.

**Comment by kwmcbride** [comment]
The parameter you added does not have the init keyword. It should be this:

builder.add_parameter('k1', init=10, bounds = (0, 1000))

Your example works for me after this change.

**Comment by notesofdabbler** [comment]
Ah, sorry I forgot to put init. You had already mentioned it previously. Thanks for clarifying again.
