### ISSUE TITLE
Issue with settings.txt after install

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#148]
I installed the current version of Kipet and when I run the command:
```
from kipet import KipetModel
```
I get an error that the file `settings.txt` is not found. I was able to resolve it by manually downloading the `settings.txt` file from the repo to the folder where kipet is installed and setting data and charts directory. But if there is a way to avoid that, it would be helpful.

**Comment by kwmcbride** [comment]
Could you please post the complete error output? I cannot recreate a missing settings.txt file error.

I did however find a bug upon closer inspection that was not handling absolute paths for the parent directory correctly. This would lead to an error in that the correct data folder could not be found. This change has been committed in the current pull request.

The current pull request changes the data folder position, how Kipet reads and writes files, and several other changes as well. If something else does not work properly in the current version, try the latest update. I made it right after the merge.

**Comment by notesofdabbler** [comment]
I cloned the current version of kipet and reinstalled it. I am still getting the settings.txt error. This [notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/Ex1_ode_sim_wk_test.ipynb) shows the error. This was the error that got resolved for me when I manually copied settings.txt file to kipet folder in the installed location

**Comment by kwmcbride** [comment]
Thanks for the full error message. I see what is going on now and have submitted the fix in #150
