### ISSUE TITLE
How do we add bounds to algebraic variables?

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#157]
I saw an example where the list of algebraics are added as below
```
# Algebraics
algebraics = ['f','r0','r1','r2','r3','r4','r5','v_sum','Csat']

r1.add_algebraic_variables(algebraics)
```
If we want to add bounds to the algebraic variables, how do we do it?

**Comment by kwmcbride** [comment]
You can do this similar to a parameter. Look at Ex_17_custom_objective.py for an example:
```
r1.add_algebraic_variables('y', init = 0.0, bounds = (0.0, 1.0))
```
