### ISSUE TITLE
Example with difficulty in fitting parameters

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#158]
I was trying to reproduce an example from Rawlings [reactor design book](https://sites.engineering.ucsb.edu/~jbraw/chemreacfun/) in this [notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_paresto/jbr_bvsm_c_red.ipynb) with Kipet - book author's octave code is [here](https://github.com/rawlings-group/paresto/blob/master/examples/green_book/bvsm_red.m). I was able to simulate with Kipet without any issues. But when I try to do parameter estimation even with initial guess close to actual parameter estimate, it doesn't seem to work. I tried some variations of nfe, ncp combinations but that didn't seem to fix it. Also, though I have put a bound of [0, 1] for `y`, the solution goes below zero.

One path I haven't tried is initializing using results from simulation. I was looking at some examples that use initializing from trajectory but wasn't sure exactly how to use it in this example.

I wanted to check if there is something I am doing incorrectly in setting up the problem. While I don't need to resolve this immediately, I would like to learn how to deal with problem instances like this in terms of any tips/tricks to make it work.

**Comment by kwmcbride** [comment]
I have actually been working on a way to streamline such initialization strategies in KIPET using simulation results. There is a method to do this in KIPET at the moment, but I find it to be too cumbersome and will make it easier to use with an option.

I will look into your notebook and see if I can identify where the issue might be. I don't think it is a big issue to fix if it is a bug.

**Comment by kwmcbride** [comment]
I am able to solve this model in my development version of KIPET. It solves pretty quickly to the correct values. You need to be careful with the number of finite elements, collocation points, and the initial value for 'y'. I have made initialization using simulation much simpler and it automatically includes custom variables outside the normally encountered variables in KIPET.
Also, sometimes it helps adding a very small value to the algebraic equations where they could approach zero. I did not need to do that in this case though.

![kipet_issue_solved](https://user-images.githubusercontent.com/47767839/105537284-add72880-5cbf-11eb-9b69-bc327c317522.png)

**Comment by notesofdabbler** [comment]
Can you share your code? What were the number of finite elements and collocation points you used? Is there a general guidance of how to set nfe and ncp?

**Comment by kwmcbride** [comment]
In the code below I did not change much. Initial values are important though. I modified your data files so that they work with the KIPET format, so you only need to change the KIPET part. The line where I add the data should be replaced by the way you added them in your example.

To get these results you will need to use the nsd_new branch in my repository.

I will try to solve your problem using the FESimulator to see if it is easier. It should be used when you have difficult to model problems that are stiff (this problem looks like that). I will load those results once I have completed them.
```
from kipet import KipetModel

kipet_model = KipetModel()

r1 = kipet_model.new_reaction('rxn1')

r1.add_component('V', state = 'state', init = 2370)
r1.add_component('eps2', state = 'concentration', init = 0.0)

r1.add_algebraic_variables('qin_B')
r1.add_algebraic_variables('nBadded')
r1.add_algebraic_variables('y1')
r1.add_algebraic_variables('y', init = 0.5, bounds = (0.0, 1.0))

r1.add_parameter('k', init = 2.28, bounds = (0, 10))
r1.add_parameter('na0', init = 2.8, bounds = (0, 10))

cbf = 0.00721
V0 = 2370

def rule_odes(m,t):
        
    exprs = dict()
    exprs['V'] = m.Y[t,'qin_B']
    exprs['eps2'] = m.Y[t, 'y1']
    return exprs

r1.add_equations(rule_odes)

r1.add_dataset(file='eli_lilly_data/flow.csv')

def rule_algebraics(m, t):
    r = list()
    r.append(m.Y[t,'nBadded'] - (m.X[t, 'V'] - V0) * cbf)
    r.append(m.Y[t,'y1'] * ((m.Y[t,'nBadded'] - 2 * m.Z[t,'eps2']) + m.P['k']*(m.P['na0'] - m.Y[t,'nBadded'] + m.Z[t, 'eps2'])) - m.Y[t,'qin_B'] * cbf * (m.Y[t,'nBadded'] - 2 * m.Z[t,'eps2']))
    r.append(m.Y[t, 'y'] * m.Y[t, 'nBadded'] - (m.Y[t,'nBadded'] - 2 * m.Z[t,'eps2']))
    return r

r1.add_algebraics(rule_algebraics)

r1.add_objective_from_algebraic('y')

r1.add_dataset('lc_data', category = 'custom', data = lc_data)
r1.add_dataset('Traj', category = 'trajectory', data = qinB_traj)

r1.fix_from_trajectory('Y', 'qin_B', 'Traj')
r1.set_times(0, 900)

# r1.settings.general.no_user_scaling = True
r1.settings.collocation.nfe = 60
r1.settings.collocation.ncp = 4
r1.settings.collocation.scheme = 'LAGRANGE-RADAU'
r1.settings.solver.linear_solver = 'ma57'

r1.settings.parameter_estimator.sim_init = True

r1.run_opt()
r1.results.plot('Z')
r1.results.plot('Y')

print(r1.results.parameters)
```

**Comment by kwmcbride** [comment]
I have tested it using FESimulator and run into similar issues. I can improve the chances of finding the correct parameter values with good initial values and by removing the bounds constraint on 'y'.

**Comment by notesofdabbler** [comment]
Thanks for the pointers above and taking a look at this issue.
