### ISSUE TITLE
Plotting Results Error

### ISSUE THREAD

**Issue by SmithCJ47** [salvadorgarciamunoz/kipet#164]
When plotting results from example files (release 0.1.3), I get the following error:
OSError: [Errno 22] Invalid argument: 'C:/Users/c304301/.spyder-py3/kipet-0.1.3/examples/example_1/charts/reaction-1-all-concentration-profiles-2021-02-25-13:05:24.html'

I believe this issue is that file names cannot contain colons ":".

**Comment by kwmcbride** [comment]
Probably an issue with Windows. I will change this in the next update.

**Comment by kwmcbride** [comment]
This is fixed in pull request #165

**Comment by kwmcbride** [comment]
Try version 0.1.4 from PyPi if you were using pip

**Comment by SmithCJ47** [comment]
Thank you! This fixed the problem!
