### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by SmithCJ47** [salvadorgarciamunoz/kipet#166]
Tried to run example 1 and received the following error. 

  File "C:\Users\c304301\Anaconda3\envs\Kipet_env\lib\site-packages\kipet\model_components\units_handler.py", line 187, in <module>
    import pytest

ModuleNotFoundError: No module named 'pytest'

I assume that pytest was left in by accident. I went in and commented it out the "import pytest" and the example ran just fine.

**Comment by kwmcbride** [comment]
I have been working on some issues with the latest package. This was an error in a new module that was used for testing. It has been removed and the new packages of KIPET will be updated tomorrow at the latest.

**Comment by SmithCJ47** [comment]
I think you essentially said it, but I wanted to confirm that commenting out that import will not break anything important.

**Comment by kwmcbride** [comment]
In that version you should delete everything below and including the import!

**Comment by kwmcbride** [comment]
If you are using pip, you can install v0.1.531. It has all the current fixes and is the most up to date.

**Comment by kwmcbride** [comment]
This issue has been fixed in the latest versions of KIPET.
