### ISSUE TITLE
Confidence intervals working in full examples

### ISSUE THREAD

**Issue by mchlshort** [salvadorgarciamunoz/kipet#18]
At this stage we only have confidence intervals working on a couple examples and it would be good if we could get them working for the large examples under Examples/Paper where the paper problems are replicated. I tried to do this but encountered errors with both replacing the current solve statement with using 'ipopt_sens' and the covariance = True options, as well as using the current example and running a new optimization beneath, initializing with the results from the working optimization.

**Comment by mchlshort** [comment]
I managed to get a couple examples working. What needs to happen is that the "user-scaling" option needs to be switched off as the scaling is for ipopt, not for ipopt_sens. Including user-scaling seems to result in an error where the linear solvers fail. Perhaps using other linear solvers (hsl) might fix this?

The second thing that seemed to fix the smaller problems was when the barrier variable initial value 'mu-init' is set to something small ( <1e-3 ).

This seems to work with the smaller examples, however a worrying problem seems to emerge when running the large examples with confidence intervals.

 ```
_compute_B_matrix
    self.B_matrix[r_idx2,c_idx] = -2*self.model.C[t,c].value/variances['device']

IndexError: index 1894 is out of bounds for axis 0 with size 1894
```

Anyone know what could be causing this?

PS. It is annoying testing for the solver options as the problem already takes a while to solve...

**Comment by schenkch** [comment]
@mchlshort: With which example do you get this error? It looks like maybe an index shift is missing.

**Comment by mchlshort** [comment]
@schenkch This is example Paper/replicate_example52a when I try and add confidence intervals

**Comment by dthierry** [comment]
@mchlshort So this happens hen you add the confidence intervals but not otherwise?
Could you provide your .py file?

**Comment by schenkch** [comment]
I set it up as well and get the same error. The problem is the predefined size of the B_matrix in the ParameterEstimator. Something is wrong with the calculation of ntheta but I haven't found out exactly what. The result for the index r_idx2 is larger than what is reserved as storage for the B_matrix.

**Comment by schenkch** [comment]
from kipet.model.TemplateBuilder import *
from kipet.sim.PyomoSimulator import *
from kipet.opt.ParameterEstimator import *
import matplotlib.pyplot as plt

from kipet.utils.data_tools import *
import inspect
import sys
import os

if __name__ == "__main__":

    with_plots = True
    if len(sys.argv)==2:
        if int(sys.argv[1]):
            with_plots = False
    
    # Load spectral data
    #################################################################################
    dataDirectory = os.path.abspath(
        os.path.join( os.path.dirname( os.path.abspath( inspect.getfile(
            inspect.currentframe() ) ) ), '..','..','data_sets'))
    filename =  os.path.join(dataDirectory,'Dij_case52a.txt')
    D_frame = read_spectral_data_from_txt(filename)

    # build dae block for optimization problems
    #################################################################################    
    builder = TemplateBuilder()    
    components = {'A':211.45e-3,'B':180.285e-3,'C':3.187e-3}
    builder.add_mixture_component(components)

    # note the parameter is not fixed
    builder.add_parameter('k1',bounds=(0.0,1.0))
    builder.add_spectral_data(D_frame)

    # define explicit system of ODEs
    def rule_odes(m,t):
        exprs = dict()
        exprs['A'] = -m.P['k1']*m.Z[t,'A']*m.Z[t,'B']
        exprs['B'] = -m.P['k1']*m.Z[t,'A']*m.Z[t,'B']
        exprs['C'] = m.P['k1']*m.Z[t,'A']*m.Z[t,'B']
        return exprs
    
    builder.set_odes_rule(rule_odes)

    pyomo_model = builder.create_pyomo_model(0.0,200.0)
        
    optimizer = ParameterEstimator(pyomo_model)

    optimizer.apply_discretization('dae.collocation',nfe=60,ncp=3,scheme='LAGRANGE-RADAU')
    
    A_set = [l for i,l in enumerate(pyomo_model.meas_lambdas) if (i % 4 == 0)]

    # Provide good initial guess
    p_guess = {'k1':0.006655}
    raw_results = optimizer.run_lsq_given_P('ipopt',p_guess,tee=False)
    
    optimizer.initialize_from_trajectory('Z',raw_results.Z)
    optimizer.initialize_from_trajectory('S',raw_results.S)
    optimizer.initialize_from_trajectory('dZdt',raw_results.dZdt)
    optimizer.initialize_from_trajectory('C',raw_results.C)



    options = dict()
    #options['mu_strategy'] = 'adaptive'
    # fixes the variances for now
    sigmas = {'device':1.94554e-5,
              'A':2.45887e-6,
              'B':2.45887e-6,
              'C':3.1296e-11}
    results_pyomo = optimizer.run_opt('ipopt_sens',
                                      tee=True,
                                      solver_options=options,
                                      variances=sigmas,
                                      tolerance=1e-4,
                                      max_iter=40,
                                      subset_lambdas=A_set,
                                      covariance=True)

    print "The estimated parameters are:"
    for k,v in results_pyomo.P.iteritems():
        print k,v

    tol = 1e-2
    assert(abs(results_pyomo.P['k1']-0.00665)<tol)
    
    # display results
    if with_plots:
        results_pyomo.C.plot.line(legend=True)
        plt.xlabel("time (s)")
        plt.ylabel("Concentration (mol/L)")
        plt.title("Concentration Profile")


        results_pyomo.S.plot.line(legend=True)
        plt.xlabel("Wavelength (cm)")
        plt.ylabel("Absorbance (L/(mol cm))")
        plt.title("Absorbance  Profile")

        plt.show()

**Comment by dthierry** [comment]
@mchlshort Do you have any idea of what ntheta should be?
It is reported that ntheta is 1894. But the index will go all the way up to 2585 which is not possible.

**Comment by dthierry** [comment]
After a couple hours of frustration I realized that the solution was in the code all the time. But it was commented out for some strange reason.
I checked the paper and the current way of indexing should work. As for the reason *why* this wasn't implemented, I cant say for sure. I suspect something is gonna break. So I just created a new branch called `fix_matrix_index_david` with the patch and the problem that Christina wrote [here](https://github.com/dthierry/kipet/blob/fix_matrix_index_david/kipet/examples/case52a/pyomo/buggy.py)

Now it works except that the assert after the solution fails.
Any inputs on this issue are welcomed.
For reference the matrix B can be found in the paper as equation `C1`.

**Comment by mchlshort** [comment]
Just to keep everyone in the loop, there seems to be some serious issues with the confidence intervals as using either method on examples 51c and 51d result in impossibly large confidence intervals.

**Comment by dthierry** [comment]
I think the fix is just rewriting parts of the B matrix. The original master version works around that but the size does not match then.

**Comment by dthierry** [comment]
@mchlshort Could you share your results for the confidence intervals of the fix vs master?

**Comment by mchlshort** [comment]
Sure, it ain't pretty though

[Confidence intervals.docx](https://github.com/dthierry/kipet/files/1943728/Confidence.intervals.docx)

Just to clarify, these are results for the examples/paper replicate studies a,b,c. With d_vars is just when I add in the with_d_vars option in the solver.

**Comment by dthierry** [comment]
I guess I should read the user's guide. I don't know all the options. 
I tried something new on the new branch `fix2dav_off`, I think some of my trials look better. But I don't know if they are *much* better.

**Comment by mchlshort** [comment]
@dthierry , you, sir, can take a bow. Your fix works great. I just finished running it on a bunch of problems and it seems to work really well! I think you can close this issue and merge into the main branch.

**Comment by dthierry** [comment]
I am glad to hear that.
