### ISSUE TITLE
python 3 Casadi and scaled_estimation fix.

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#34]
These problems happen whenever we try to use python 3.

**Comment by mchlshort** [comment]
There still seems to be whatevs.nl generating as well.

**Comment by dthierry** [comment]
Ah, the elusive `whatevs.nl`. I will try to kill it once for all.

**Comment by dthierry** [comment]
BTW, I created a new branch with a *fix* although I am not sure about it yet. I need to think about it more thoroughly.

**Comment by mchlshort** [comment]
Hi @dthierry was wondering if you managed to quash the 'whatevs.nl' in the fix? I haven't run it yet. Also, do you think we are good to go for the release of version 1.0?

**Comment by dthierry** [comment]
Not yet, but I will by the end the day.

**Comment by dthierry** [comment]
Alright, I think it is done. I will merge to master now.

**Comment by mchlshort** [comment]
Looks to be all sorted
