### ISSUE TITLE
license

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#40]
Just for [reference](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)).

**Comment by mchlshort** [comment]
Thanks @dthierry , I will include a link to that in the e-mail. It looks like the kind of thing that Sal mentioned; or at least what was understood.

**Comment by dthierry** [comment]
I hope it is, time to lawyer up.

**Comment by mchlshort** [comment]
Ok, I guess GPL-3 it is, so we can close this issue
