### ISSUE TITLE
Test fe_factory on the aspirin problem.

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#45]
As Sal noted, this problem seems to a good case study for verification.

**Comment by mchlshort** [comment]
Hi @dthierry , that is a great idea.

 I have been trying to get it up and running, but been having issues with providing the fe_factory the right information. I have tried a variety of things, but I am not sure which equations or variables are missing as I can't seem to get the numbers of equations and variables to match. I am including the .py as a .txt as Github won't allow me to upload with that file extension.

[aspirin_sim_fe_factory.txt](https://github.com/salvadorgarciamunoz/kipet/files/2036948/aspirin_sim_fe_factory.txt)

I am probably doing something really stupid :/

If someone can have a look at it, or come have a chat with me when you return, that would be great.

**Comment by mchlshort** [comment]
Created a new branch for tinkering with fe_factory and the new example.

The problem (which is not working yet) is here:

https://github.com/salvadorgarciamunoz/kipet/blob/fe_example_branch/kipet/validation/test_problems/aspirin_sim_fe_factory_new_try.py

**Comment by dthierry** [comment]
Ah I have the problem now; you need to do something like:
```python
inputs_sub['Y'] = ['f', 'Csat']
```
That should fix it.
The problem now it that it seems we need to declare bounds inside `fe_factory`.

**Comment by dthierry** [comment]
So, I've tried to solve the problem with the new bounds and something weird happens. There are 470 points in the data (inputs) but if you declare the discretization with more/less finite elements `fe_factory` will usually fail.
My intuition tells me that if the number of data inputs and number of available points is not consistent this should fail, which is the case. 
For example, declare 500 finite elements (there are only 470 data inputs), and `fe_factory` will try to fetch the inputs for 500 time points but not fail :| somehow. Then, it will try to solve and fail. 
Anyway, here is the [branch](https://github.com/salvadorgarciamunoz/kipet/tree/fix_fe_fact) with the changes ..

**Comment by dthierry** [comment]
Also, I've found that the negative *f* values are generated somehow from a *sort-of* interpolation. This should be at least deactivated for a `fe_factory` problem.

**Comment by mchlshort** [comment]
Just wanted to close this off as the new versions of fe_factory, in combination with a slight change to the Heaviside step function now has solved this problem. The results are not perfect, but neither was the original simulation model. I am closing this for now and uploading the new, working aspirin example.
