### ISSUE TITLE
Discrete jump feeding strategy

### ISSUE THREAD

**Issue by schenkch** [salvadorgarciamunoz/kipet#56]
I created a new branch called discrete_feeds where I included the code for feeds of a discrete jump in time. So far it only works for a single feed for one component though. There is a new example called Ex_5_sim_fe_by_fe_testjump.py where I included a jump. I also tested it for the other fe_factory examples. @mchlshort: Maybe you can test this again also varying the number of collocation points?

**Comment by mchlshort** [comment]
Great, thanks. I will do that and let you know how it goes.

**Comment by schenkch** [comment]
I think I got the multiple input version working as well but that still requires intense testing for other inputs and examples. The files are in the same branch but called differently with the mult ending. It would be great if you had a look at it as well @dthierry and @mchlshort .

**Comment by mchlshort** [comment]
Hi Christina, just wanted to follow up on our previous chat, whenever you have time to add in the option to add feeding in of other algebraic states ('X') then I think that this branch is ready to be merged. I tested it and it looks pretty good from what I can tell.

**Comment by schenkch** [comment]
Hi Mike, that already works. I tested it again and I included more exceptions and extensions as well. I just have to clean up the code and then I will upload a new version with a new example with also algebraic jumps to make clear how it works with the syntax.

**Comment by mchlshort** [comment]
Ok great, thanks Christina :)

**Comment by schenkch** [comment]
I created a new branch called multiple_inputs that includes the new files. Maybe you can test that as well @mchlshort . I also created an example with additional temperature inputs. Did the aspirin_fe-factory examples work at some point?

**Comment by mchlshort** [comment]
Ok, great, I will test it and let you know how it goes. Alas, aspirin_fe_factory has never worked... Similar issue that we were discussing with Larry and that you were having.
