### ISSUE TITLE
k_aug error on C-data problems

### ISSUE THREAD

**Issue by mchlshort** [salvadorgarciamunoz/kipet#58]
k_aug seems to run into memory problems when running the concentration input problems. It works well for the regular spectroscopic problems. the example with the error is 'Ex_7_conc_input_conf_k_aug.py' in the 'k_aug_in' branch.

**Comment by mchlshort** [comment]
Hi @dthierry , was wondering if you managed to fix this yet? Is k_aug up to date on the master branch? If it is ready, I will update my version of k_aug and do some tests before we merge the k_aug_in branch.

**Comment by dthierry** [comment]
Hi Mike, Ex 7 was the only one right?

How does this look to you?
**k_aug:**
Parameter variances:  [2.47995798e-06 7.37134303e-08]

Confidence intervals:
k2 (1.02867157494,1.0318211514)
k1 (0.22641857464,0.226961578988)
The estimated parameters are:
k2 1.03024636317
k1 0.226690076814
**sipopt**
Parameter variances:  [2.50531581e-06 7.59866353e-08]

Confidence intervals:
k2 (1.02866354425,1.03182918214)
k1 (0.226414420081,0.22696573355)
k2 1.03024636319
k1 0.226690076814

Please, let me know.

**Comment by mchlshort** [comment]
It looks beautiful. Seems to be working nicely now. So that was just a k_aug fix, right? No additions in Kipet?

**Comment by dthierry** [comment]
Alright Mike, I think you can try again with the master branch of k_aug. I didn't change anything from kipet.

**Comment by mchlshort** [comment]
Hi @dthierry , I can confirm that it is working well now. Still working on getting it working on Windows, however that is a k_aug issue, so I will maybe move my comments over there. This issue can be closed now.
