### ISSUE TITLE
Mixture component/complementary states w/o odes

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#6]
Every mixture component/complementary state must have an ode.
Is there a counter example of this @mchlshort ?

>     components = {'A': 1e-3, 'B': 0, 'C': 0}  #: Components A, B, C
>     ...
>     # define explicit system of ODEs
>     def rule_odes2(m, t):
>         exprs = dict()
>         exprs['A'] = -m.P['k1'] * m.Z[t, 'A']
>         exprs['B'] = m.P['k1'] * m.Z[t, 'A'] - m.P['k2'] * m.Z[t, 'B']
>         exprs['C'] = m.P['k2'] * m.Z[t, 'B']
>         return exprs  #: Expression for A, B and C. Otherwise this would be wrong.
> 

I suggest throw an Exception whenever somebody misses an ODE.

**Comment by mchlshort** [comment]
Hi @dthierry I think that we might need to include non-reacting components in the future that end up absorbing and still need to be taken into account. It is not a bad idea, but we might need to think a bit more about that. Let me know if you don't agree or if I am maybe missing something.

**Comment by mchlshort** [comment]
Great, as we noted in our discussion, we will be throwing an exception whenever an ODE is missing. If a component absorbs and does not react an ODE can be added that just ensures that the component concentration does not change with time. I will note this in the manual  as well.
