### ISSUE TITLE
Create installation manual

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#7]
I recommend using pip and so forth.
How to get and install ipopt.
How to get and install python-pip.
How to install the dependencies.
How to install kipet.

**Comment by mchlshort** [comment]
Good idea. I will also work on this and include in the manual

**Comment by mchlshort** [comment]
I have finished the installation manual and included it in the documentation. Just going to close this thread so that things look a little less cluttered.
