### ISSUE TITLE
Consider the case of an absorbing specie that has no role in the kinetics

### ISSUE THREAD

**Issue by salvadorgarciamunoz** [salvadorgarciamunoz/kipet#70]
Perhaps this is already doable, let's create an example where a solvent added is diluting but not necessarily contributing to the reactions.

**Comment by mchlshort** [comment]
I am busy working on this. Already included is the ability to do this where the diluting species' absorbance profile is not known and is estimated along with the other reacting components. I will include an example in my next commit. What is not included and will now also be possible in the next addition is for a species (that takes part in the reaction or not) to be included with a known absorbance profile.

**Comment by mchlshort** [comment]
Newest pull request features this new ability including the ability to both estimate the interfering species' absorbance or to fix the absorbance of species. Examples showing this:

"Ex_2_abs_known_non_react.py"

"Ex_2_abs_not_react.py"
