### ISSUE TITLE
Create a comprehensible documentation (.pdf included)

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#8]
As Sal noted.

**Comment by mchlshort** [comment]
Hi David, I have already started a document as I work through all the code that will hopefully provide a step-by-step breakdown of what to include and why in each type of problem to be solved. Leave this part to me, as I feel that it is beneficial to my understanding of the software and coding to produce this. I will include parts of what is already there and include a more detailed breakdown as well.

**Comment by mchlshort** [comment]
Here is a first draft of the documentation. If there are any glaring omissions please let me know. Edits/comments are welcome. The highlighted sections are just things that might still need a bit of work or comments. 

[Kipet documentation version 0.7329.docx](https://github.com/dthierry/kipet/files/1939724/Kipet.documentation.version.0.7329.docx)

**Comment by mchlshort** [comment]
Just wanted to ask you guys if you have sIpopt working on Windows? If you do, how do you do it? I tried this afternoon to get it working on 2 separate machines and failed both times using Cygwin and following the steps suggested. My feeling is that the installation instructions up on COIN-OR were written for an older version of Cygwin and some of the dependencies that are required to compile Ipopt have now been excluded with the current version.

I had gotten Ipopt working with no problems as the precompiled binaries were available, however there seems to be no precompiled binaries for sIpopt available online.

Any help or comments would be appreciated as I would like to get it working and include it in the user guide.

**Comment by dthierry** [comment]
I will try the installation of sipopt later on today. I will let you know what I find.

**Comment by dthierry** [comment]
[Ipopt_sIpopt_Installation_on_Windows_cygwin.pdf](https://github.com/dthierry/kipet/files/1959417/Ipopt_sIpopt_Installation_on_Windows_cygwin.pdf)
@mchlshort I blatantly stole this guide from the IDAES group. I haven't tried myself but as far as I remember the tricky part is get the patches for `make` in cygwin.

**Comment by schenkch** [comment]
I read over the kipet documentation uploaded by Michael and just added a few comments, modifications and some additional information. You can find them highlighted in green in the following document: 
[Kipet.documentation.changesChris.docx](https://github.com/dthierry/kipet/files/1959550/Kipet.documentation.changesChris.docx)

**Comment by mchlshort** [comment]
Thanks a lot @schenkch . I fixed the typos and included your corrections. Will work on adding in the final functionalities once everything is finalized and upload a more complete looking document soon.

**Comment by mchlshort** [comment]
Hi @dthierry, Thanks so much, I got it up and running now. It is pretty annoying that the instructions on the COIN-OR website are out of date. Any link for these instructions that I can put in the manual? Or should I re-write them in?

**Comment by dthierry** [comment]
I think that the guide is not public yet. So maybe just put it in, and an acknowledgement to `IDAES - Ipopt $ sIpopt installation V01`  by AKULA PAUL.

**Comment by schenkch** [comment]
We should probably include a short description and refer to the examples for the element by element implementation and the known non absorbing species implementation. @mchlshort: Have you already done that? Otherwise I can take care of that as well if you send me the most recent version of the documentation.

**Comment by mchlshort** [comment]
Hi @schenkch, I agree and have been thinking about it but I haven't gotten to it yet. If you could do that it would be great. I am busy commenting and adding examples (the table just before section 5).

Here is the latest version: 
[Kipet documentation version 0.91.docx](https://github.com/dthierry/kipet/files/1964714/Kipet.documentation.version.0.91.docx)

**Comment by mchlshort** [comment]
And just a heads up that I will add a new folder that has fewer examples and fewer repeats of examples for the user where the filenames are a bit less confusing and repetitive. I am also not sure how the fe_factory can be used to initialize the ParameterEstimator as we do not have an example for that. If you know how to implement that, can you try and include an example of it?

**Comment by schenkch** [comment]
@mchlshort: Attached you find a version of the documentation where I added two short tutorials under 4.5 and 4.6. mostly highlighted in green again (just before section 5). 
[Kipet.documentation.version.0.91_chris.docx](https://github.com/dthierry/kipet/files/1965351/Kipet.documentation.version.0.91_chris.docx)

**Comment by mchlshort** [comment]
Documentation is all but finished. The branch `user-friendly` includes the new documentation and the previous documentation is deleted as the new one includes all the useful parts of that documentation. It is not yet a pdf as it still needs the link to the final hosting site as well as the licence.

**Comment by schenkch** [comment]
I read over the documentation again an uploaded the modified version as Kipet documentation version 0.99b.odt in the back_to_fixes branch.

**Comment by mchlshort** [comment]
Ok, great, I have now updated that Ex_6_non_abs with one that works (i.e. it no longer has a flat conc. profile for C) and I have also added that into the documentation. Docs are now good to go apart from the licence and hosting site

**Comment by mchlshort** [comment]
Guess we are good to go on this. Any changes now will be very minor and dealt with quickly and easily
