### ISSUE TITLE
k_aug issue with Windows10

### ISSUE THREAD

**Issue by schenkch** [salvadorgarciamunoz/kipet#94]
Some of the examples do not work with k_aug under Windows10, such as examples Ex_2_estimation_conf_k_aug.py and Ex_2_estimationfefactoryTempV.py.

**Comment by dthierry** [comment]
I'll check. I hope it is not k_aug related.
Could you provide the output of the following commands:

uname -u
(at your venv) pip freeze.
Thanks.

**Comment by schenkch** [comment]
Thanks @dthierry 
This is the output from k_aug:
{'A': 1.0886992699221108e-10, 'device': 3.288879007726867e-06, 'C': 9.627812050056525e-11, 'B': 1.6456485374596862e-10}
        6.03 seconds required to write file
        6.16 seconds required for presolve
        9.87 seconds required for solver
        0.00 seconds required to read logfile
        0.59 seconds required to read solution file
        0.84 seconds required for postsolve
ERROR: Solver (asl) returned non-zero return code (-1073741819)
ERROR: Solver log: [K_AUG] written by D.T. @2018

    : W[K_AUG]...   [K_AUG_ASL]No n_rhs declared W[K_AUG]...
    [K_AUG_ASL]Target log10mu:= -11. W[K_AUG]...    [K_AUG_ASL]No f_timestamp
    suffix declared, Fallback to default writing mode. I[K_AUG]...
    [K_AUG_ASL] Filename for dot_sens dot_in_.in
Traceback (most recent call last):
  File "Ex_2_estimation_conf_k_aug.py", line 136, in <module>
    covariance=True)
  File "C:\Users\Christina\Anaconda3\envs\kipet0412conda\lib\site-packages\kipet-1.0.92-py2.7.egg\kipet\library\ParameterEstimator.py", line 1033, in run_opt
    **kwds)
  File "C:\Users\Christina\Anaconda3\envs\kipet0412conda\lib\site-packages\kipet-1.0.92-py2.7.egg\kipet\library\ParameterEstimator.py", line 232, in _solve_extended_model
    k_aug.solve(m, tee=False)
  File "C:\Users\Christina\Anaconda3\envs\kipet0412conda\lib\site-packages\pyomo-5.6.1-py2.7.egg\pyomo\opt\base\solvers.py", line 596, in solve
    "Solver (%s) did not exit normally" % self.name)
pyutilib.common._exceptions.ApplicationError: Solver (asl) did not exit normally

I guess you meant uname -a:
(kipet0412conda) C:\Users\Christina\Documents\kipet-master0412\kipet\examples>uname -a
CYGWIN_NT-10.0 DESKTOP-4BUBIU8 3.0.6(0.338/5/3) 2019-04-06 16:18 x86_64 Cygwin

I attached the output of pip freeze in a txt file. 
[pythonvers.txt](https://github.com/salvadorgarciamunoz/kipet/files/3100493/pythonvers.txt)

**Comment by dthierry** [comment]
Ah, thanks.
I think we have the same CYGWIN version. However the python packages are different ([my_packages.txt](https://github.com/salvadorgarciamunoz/kipet/files/3100581/my_packages.txt)). 
I am able to solve Ex_2_estimation_conf_k_aug.py [success1.txt](https://github.com/salvadorgarciamunoz/kipet/files/3100572/success1.txt)

For the second file I get the following:

> Traceback (most recent call last):
>   File "Ex_2_estimationfefactoryTempV.py", line 333, in <module>
>     feed_times=feed_times
>   File "c:\cygwin64\home\david\kipet\kipet\library\ParameterEstimator.py", line 1033, in run_opt
>     **kwds)
>   File "c:\cygwin64\home\david\kipet\kipet\library\ParameterEstimator.py", line 232, in _solve_extended_model
>     k_aug.solve(m, tee=False)
>   File "C:\cygwin64\home\David\kipet\v\lib\site-packages\pyomo\opt\base\solvers.py", line 596, in solve
>     "Solver (%s) did not exit normally" % self.name)
> pyutilib.common._exceptions.ApplicationError: Solver (asl) did not exit normally

And I think the reason is that your KKT matrix is numerically singular (`[check](http://mumps.enseeiht.fr/doc/userguide_5.2.0.pdf)`)
Here is my output:  [failure2.txt](https://github.com/salvadorgarciamunoz/kipet/files/3100576/failure2.txt)

Are you able to solve both on linux?

**Comment by schenkch** [comment]
Thanks, that is weird. Yes, on linux all the examples work and it is not a problem on Windows8 either.
Yes, that is what I thought as well but it is strange that that just happens on Windows10.

**Comment by dthierry** [comment]
Follow-up:
k_aug with ma57 is able to solve both problems in Windows 10
It also works on macOS.
Caveat: ma57 license is required.
![Screen Shot 2019-07-05 at 8 50 21 PM](https://user-images.githubusercontent.com/16341267/60749358-d5905f80-9f66-11e9-8e1d-4063238372d5.png)
